export interface EmojiEntry {
  char: string
  names: string[]
}

// Primary name is names[0]; all names are used for matching.
export const EMOJI_LIST: EmojiEntry[] = [
  // Smileys & Emotions
  { char: '😀', names: ['grinning', 'happy', 'smile', 'grin'] },
  { char: '😃', names: ['smiley', 'big_smile', 'happy'] },
  { char: '😄', names: ['smile', 'happy', 'joy'] },
  { char: '😁', names: ['grin', 'beaming'] },
  { char: '😆', names: ['laughing', 'satisfied', 'lol'] },
  { char: '😅', names: ['sweat_smile', 'nervous_laugh'] },
  { char: '🤣', names: ['rofl', 'rolling_laughing'] },
  { char: '😂', names: ['joy', 'tears_of_joy', 'crying_laughing', 'lol'] },
  { char: '🙂', names: ['slightly_smiling', 'smile'] },
  { char: '🙃', names: ['upside_down', 'silly'] },
  { char: '😉', names: ['wink', 'winking'] },
  { char: '😊', names: ['blush', 'smile', 'happy', 'shy'] },
  { char: '😇', names: ['innocent', 'halo', 'angel'] },
  { char: '🥰', names: ['smiling_hearts', 'love', 'adore', 'smitten'] },
  { char: '😍', names: ['heart_eyes', 'love', 'beautiful', 'gorgeous'] },
  { char: '🤩', names: ['star_struck', 'excited', 'wow', 'starstruck'] },
  { char: '😘', names: ['kissing_heart', 'kiss', 'love', 'mwah'] },
  { char: '😋', names: ['yum', 'delicious', 'tasty', 'lick'] },
  { char: '😜', names: ['wink_tongue', 'silly', 'playful'] },
  { char: '🤪', names: ['zany', 'crazy', 'wild', 'silly'] },
  { char: '🤑', names: ['money_mouth', 'rich', 'greedy'] },
  { char: '🤗', names: ['hugging', 'hug', 'embrace', 'warm'] },
  { char: '🤭', names: ['hand_over_mouth', 'giggle', 'secret', 'oops'] },
  { char: '🤫', names: ['shushing', 'quiet', 'ssh', 'silence', 'shh'] },
  { char: '🤔', names: ['thinking', 'hmm', 'pondering', 'consider'] },
  { char: '🤐', names: ['zipper_mouth', 'silent', 'sealed_lips'] },
  { char: '🤨', names: ['raised_eyebrow', 'skeptical', 'suspicious'] },
  { char: '😐', names: ['neutral_face', 'meh', 'blank'] },
  { char: '😑', names: ['expressionless', 'blank', 'deadpan'] },
  { char: '😏', names: ['smirk', 'smug', 'sly'] },
  { char: '😒', names: ['unamused', 'unimpressed', 'whatever'] },
  { char: '🙄', names: ['eye_roll', 'rolling_eyes', 'eyeroll'] },
  { char: '😬', names: ['grimacing', 'nervous', 'awkward', 'yikes'] },
  { char: '🤥', names: ['lying', 'pinocchio', 'liar'] },
  { char: '😌', names: ['relieved', 'content', 'peaceful'] },
  { char: '😔', names: ['pensive', 'sad', 'thoughtful', 'down'] },
  { char: '😪', names: ['sleepy', 'tired', 'drowsy'] },
  { char: '😴', names: ['sleeping', 'zzz', 'tired', 'sleep'] },
  { char: '😷', names: ['mask', 'sick', 'medical', 'covid'] },
  { char: '🤢', names: ['nauseated', 'sick', 'gross', 'nauseous'] },
  { char: '🤮', names: ['vomiting', 'sick', 'puke', 'barf'] },
  { char: '🤧', names: ['sneezing', 'cold', 'sick', 'sneeze'] },
  { char: '🥵', names: ['hot_face', 'hot', 'sweating', 'burning'] },
  { char: '🥶', names: ['cold_face', 'cold', 'freezing', 'frozen'] },
  { char: '🥴', names: ['woozy', 'dizzy', 'drunk', 'tipsy'] },
  { char: '🤯', names: ['exploding_head', 'mindblown', 'shocked', 'mind_blown'] },
  { char: '🤠', names: ['cowboy', 'hat', 'yeehaw', 'western'] },
  { char: '🥳', names: ['partying', 'party', 'celebrate', 'birthday'] },
  { char: '😎', names: ['sunglasses', 'cool', 'awesome', 'chill'] },
  { char: '🤓', names: ['nerd', 'glasses', 'smart', 'geek'] },
  { char: '🧐', names: ['monocle', 'curious', 'investigate', 'fancy'] },
  { char: '😕', names: ['confused', 'meh', 'puzzled'] },
  { char: '😟', names: ['worried', 'concern', 'anxious'] },
  { char: '😮', names: ['open_mouth', 'surprised', 'wow', 'gasp'] },
  { char: '😲', names: ['astonished', 'shocked', 'wow', 'omg'] },
  { char: '😳', names: ['flushed', 'embarrassed', 'shocked', 'blushing'] },
  { char: '🥺', names: ['pleading', 'puppy_eyes', 'begging', 'uwu'] },
  { char: '😨', names: ['fearful', 'scared', 'afraid', 'fear'] },
  { char: '😰', names: ['anxious_sweat', 'nervous', 'sweating'] },
  { char: '😢', names: ['cry', 'crying', 'sad', 'tear', 'unhappy'] },
  { char: '😭', names: ['loudly_crying', 'sob', 'cry', 'bawling'] },
  { char: '😱', names: ['scream', 'scared', 'horror', 'shocked', 'screaming'] },
  { char: '😩', names: ['weary', 'exhausted', 'tired', 'ugh'] },
  { char: '🥱', names: ['yawning', 'tired', 'bored', 'yawn'] },
  { char: '😤', names: ['triumph', 'frustrated', 'huffing', 'annoyed'] },
  { char: '😡', names: ['pouting', 'angry', 'mad', 'rage', 'pissed'] },
  { char: '😠', names: ['angry', 'mad', 'anger', 'grumpy'] },
  { char: '🤬', names: ['cursing', 'swearing', 'angry', 'rage', 'expletive'] },
  { char: '😈', names: ['smiling_devil', 'evil', 'horns', 'mischievous'] },
  { char: '👿', names: ['angry_devil', 'evil', 'imp', 'demon'] },
  { char: '💀', names: ['skull', 'dead', 'death', 'rip'] },
  { char: '💩', names: ['poop', 'poo', 'shit', 'crap'] },
  { char: '👻', names: ['ghost', 'halloween', 'boo', 'spooky'] },
  { char: '🤖', names: ['robot', 'bot', 'android', 'machine', 'ai'] },
  // Gestures & Hands
  { char: '👋', names: ['wave', 'waving', 'hi', 'hello', 'bye', 'hey'] },
  { char: '✋', names: ['raised_hand', 'stop', 'high_five', 'halt'] },
  { char: '👌', names: ['ok_hand', 'okay', 'perfect', 'ok'] },
  { char: '✌️', names: ['victory', 'peace', 'v', 'two', 'peace_sign'] },
  { char: '🤞', names: ['crossed_fingers', 'luck', 'hoping', 'fingers_crossed'] },
  { char: '🤘', names: ['horns', 'rock_on', 'metal', 'devil_horns'] },
  { char: '🤙', names: ['call_me', 'shaka', 'hang_loose', 'phone'] },
  { char: '👈', names: ['point_left', 'left', 'arrow_left'] },
  { char: '👉', names: ['point_right', 'right', 'arrow_right', 'this'] },
  { char: '👆', names: ['point_up', 'up', 'above'] },
  { char: '👇', names: ['point_down', 'down', 'below'] },
  { char: '👍', names: ['thumbs_up', 'like', 'good', 'ok', 'approve', 'yes', '+1'] },
  { char: '👎', names: ['thumbs_down', 'dislike', 'bad', 'no', '-1'] },
  { char: '✊', names: ['raised_fist', 'fist', 'punch', 'bump', 'solidarity'] },
  { char: '👊', names: ['oncoming_fist', 'punch', 'fist_bump', 'bam'] },
  { char: '👏', names: ['clap', 'clapping', 'applause', 'bravo', 'clapping_hands'] },
  { char: '🙌', names: ['raised_hands', 'hooray', 'celebrate', 'praise', 'hallelujah'] },
  { char: '🙏', names: ['folded_hands', 'pray', 'thanks', 'please', 'namaste', 'thank_you'] },
  { char: '💪', names: ['muscle', 'flex', 'strong', 'strength', 'bicep'] },
  { char: '👀', names: ['eyes', 'look', 'watching', 'stare', 'see', 'lurking'] },
  { char: '🫶', names: ['heart_hands', 'love', 'heart', 'care'] },
  { char: '🤝', names: ['handshake', 'deal', 'agree', 'shake'] },
  { char: '🫂', names: ['people_hugging', 'hug', 'comfort', 'support'] },
  // Hearts
  { char: '❤️', names: ['heart', 'love', 'red_heart', 'romantic'] },
  { char: '🧡', names: ['orange_heart', 'love', 'orange'] },
  { char: '💛', names: ['yellow_heart', 'love', 'yellow', 'friendship'] },
  { char: '💚', names: ['green_heart', 'love', 'green', 'nature'] },
  { char: '💙', names: ['blue_heart', 'love', 'blue'] },
  { char: '💜', names: ['purple_heart', 'love', 'purple'] },
  { char: '🖤', names: ['black_heart', 'dark', 'evil'] },
  { char: '🤍', names: ['white_heart', 'pure', 'love'] },
  { char: '💔', names: ['broken_heart', 'heartbreak', 'sad', 'heartbroken'] },
  { char: '💕', names: ['two_hearts', 'love', 'couple'] },
  { char: '💖', names: ['sparkling_heart', 'love', 'glitter'] },
  { char: '💗', names: ['growing_heart', 'love', 'beating'] },
  { char: '💘', names: ['heart_arrow', 'cupid', 'love', 'crush'] },
  // Nature & Symbols
  { char: '🔥', names: ['fire', 'flame', 'hot', 'lit', 'blazing', 'burn', 'heat'] },
  { char: '✨', names: ['sparkles', 'glitter', 'magic', 'star', 'shiny', 'sparkle'] },
  { char: '⚡', names: ['lightning', 'zap', 'electric', 'bolt', 'thunder', 'fast'] },
  { char: '🌟', names: ['glowing_star', 'star', 'shiny', 'great'] },
  { char: '⭐', names: ['star', 'yellow_star', 'favorite'] },
  { char: '🌙', names: ['crescent_moon', 'moon', 'night', 'sleep'] },
  { char: '☀️', names: ['sun', 'sunny', 'bright', 'sunshine', 'day'] },
  { char: '🌈', names: ['rainbow', 'colorful', 'pride', 'colors'] },
  { char: '❄️', names: ['snowflake', 'cold', 'winter', 'snow', 'freeze'] },
  { char: '🌊', names: ['wave', 'ocean', 'surf', 'water', 'sea'] },
  { char: '🌸', names: ['cherry_blossom', 'flower', 'pink', 'spring'] },
  { char: '🌺', names: ['hibiscus', 'flower', 'tropical'] },
  { char: '🌻', names: ['sunflower', 'flower', 'yellow', 'sun'] },
  { char: '🌹', names: ['rose', 'flower', 'red', 'romance'] },
  { char: '🍀', names: ['four_leaf_clover', 'luck', 'lucky', 'green'] },
  { char: '🌿', names: ['herb', 'leaf', 'plant', 'nature', 'green'] },
  { char: '🍁', names: ['maple_leaf', 'autumn', 'fall', 'canada'] },
  { char: '🌍', names: ['earth', 'globe', 'world', 'global'] },
  { char: '🌎', names: ['earth_americas', 'globe', 'world'] },
  { char: '🌏', names: ['earth_asia', 'globe', 'world'] },
  // Animals
  { char: '🐶', names: ['dog', 'puppy', 'woof', 'doggo'] },
  { char: '🐱', names: ['cat', 'kitty', 'meow', 'kitten'] },
  { char: '🐻', names: ['bear', 'bear_face', 'teddy'] },
  { char: '🐼', names: ['panda', 'cute', 'bear'] },
  { char: '🐨', names: ['koala', 'cute', 'australia'] },
  { char: '🦁', names: ['lion', 'roar', 'brave', 'king'] },
  { char: '🐯', names: ['tiger', 'striped', 'cat'] },
  { char: '🦊', names: ['fox', 'foxy', 'clever'] },
  { char: '🐺', names: ['wolf', 'howl', 'wild'] },
  { char: '🦋', names: ['butterfly', 'transform', 'pretty', 'wings'] },
  { char: '🐛', names: ['bug', 'caterpillar', 'worm', 'insect'] },
  { char: '🐝', names: ['bee', 'honeybee', 'busy', 'sting'] },
  { char: '🐢', names: ['turtle', 'slow', 'tortoise', 'shell'] },
  { char: '🐍', names: ['snake', 'serpent', 'python', 'slither'] },
  { char: '🦕', names: ['dinosaur', 'sauropod', 'dino'] },
  { char: '🦖', names: ['trex', 'dinosaur', 'rex', 'dino'] },
  { char: '🐙', names: ['octopus', 'tentacles', 'sea'] },
  { char: '🦈', names: ['shark', 'ocean', 'danger', 'jaws'] },
  { char: '🐬', names: ['dolphin', 'ocean', 'smart', 'flipper'] },
  { char: '🐳', names: ['whale', 'ocean', 'big', 'blue_whale'] },
  { char: '🐸', names: ['frog', 'ribbit', 'green', 'kermit'] },
  { char: '🐧', names: ['penguin', 'tux', 'linux', 'cold'] },
  // Food
  { char: '🍕', names: ['pizza', 'slice', 'food', 'italian'] },
  { char: '🍔', names: ['burger', 'hamburger', 'food', 'fast_food'] },
  { char: '🌮', names: ['taco', 'mexican', 'food'] },
  { char: '🍜', names: ['ramen', 'noodles', 'soup', 'food', 'pasta'] },
  { char: '🍣', names: ['sushi', 'japanese', 'food', 'fish'] },
  { char: '🍩', names: ['donut', 'doughnut', 'sweet', 'dessert'] },
  { char: '🍪', names: ['cookie', 'biscuit', 'treat', 'sweet'] },
  { char: '🎂', names: ['birthday_cake', 'birthday', 'celebration', 'cake'] },
  { char: '🍰', names: ['cake', 'slice_of_cake', 'dessert'] },
  { char: '🍫', names: ['chocolate', 'candy', 'sweet', 'choco'] },
  { char: '☕', names: ['coffee', 'hot_drink', 'cafe', 'espresso', 'morning'] },
  { char: '🍵', names: ['tea', 'teacup', 'green_tea', 'hot'] },
  { char: '🧃', names: ['juice_box', 'drink', 'juice'] },
  { char: '🍺', names: ['beer', 'cheers', 'drink', 'brew'] },
  { char: '🍻', names: ['beers', 'cheers', 'clinking', 'toast', 'celebrate'] },
  { char: '🥂', names: ['champagne', 'toast', 'celebrate', 'clinking_glasses', 'prosecco'] },
  { char: '🍷', names: ['wine', 'red_wine', 'drink', 'vino'] },
  { char: '🥃', names: ['whiskey', 'tumbler', 'spirits', 'scotch'] },
  { char: '🍹', names: ['tropical_drink', 'cocktail', 'vacation', 'margarita'] },
  // Objects & Tech
  { char: '💻', names: ['laptop', 'computer', 'macbook', 'coding', 'code'] },
  { char: '🖥️', names: ['desktop', 'monitor', 'screen', 'display', 'computer'] },
  { char: '📱', names: ['iphone', 'phone', 'mobile', 'smartphone', 'cell'] },
  { char: '⌨️', names: ['keyboard', 'type', 'keys', 'typing'] },
  { char: '🖱️', names: ['mouse', 'cursor', 'click', 'computer'] },
  { char: '📷', names: ['camera', 'photo', 'picture', 'snapshot'] },
  { char: '🎥', names: ['video_camera', 'movie', 'film', 'record'] },
  { char: '📺', names: ['tv', 'television', 'screen', 'watch'] },
  { char: '📡', names: ['satellite', 'antenna', 'signal', 'broadcast', 'dish'] },
  { char: '🔭', names: ['telescope', 'astronomy', 'space', 'stars', 'observe'] },
  { char: '🔬', names: ['microscope', 'lab', 'science', 'biology', 'research'] },
  { char: '💡', names: ['bulb', 'light', 'idea', 'bright', 'lightbulb', 'tip'] },
  { char: '🔑', names: ['key', 'access', 'unlock', 'password'] },
  { char: '🔒', names: ['lock', 'locked', 'secure', 'private', 'closed'] },
  { char: '🔓', names: ['unlock', 'unlocked', 'open', 'access'] },
  { char: '🔧', names: ['wrench', 'tool', 'fix', 'settings', 'maintenance'] },
  { char: '🔨', names: ['hammer', 'build', 'tool', 'construction'] },
  { char: '⚙️', names: ['gear', 'settings', 'config', 'cog', 'engineering'] },
  { char: '🛠️', names: ['tools', 'wrench', 'build', 'construction', 'fix'] },
  { char: '🗑️', names: ['trash', 'delete', 'bin', 'garbage', 'remove', 'waste'] },
  { char: '📦', names: ['package', 'box', 'parcel', 'deploy', 'ship', 'shipping'] },
  { char: '📁', names: ['folder', 'directory', 'files'] },
  { char: '📂', names: ['open_folder', 'directory', 'files'] },
  { char: '📄', names: ['page', 'document', 'file', 'paper', 'doc'] },
  { char: '📝', names: ['pencil', 'memo', 'write', 'note', 'edit', 'notes'] },
  { char: '✏️', names: ['pencil', 'edit', 'write', 'draw'] },
  { char: '🔍', names: ['search', 'magnifying_glass', 'find', 'look', 'zoom_in'] },
  { char: '🔎', names: ['search_right', 'magnifying_glass', 'find', 'zoom_out'] },
  { char: '📊', names: ['bar_chart', 'graph', 'stats', 'data', 'analytics', 'chart'] },
  { char: '📈', names: ['chart_up', 'graph', 'growth', 'increase', 'up', 'trending'] },
  { char: '📉', names: ['chart_down', 'graph', 'decline', 'decrease', 'down'] },
  { char: '🔗', names: ['link', 'chain', 'url', 'hyperlink', 'chain_link'] },
  { char: '💾', names: ['floppy_disk', 'save', 'storage', 'disk', 'floppy'] },
  { char: '💿', names: ['cd', 'disc', 'disk', 'optical'] },
  { char: '📤', names: ['outbox', 'send', 'upload', 'out', 'export'] },
  { char: '📥', names: ['inbox', 'receive', 'download', 'in', 'import'] },
  { char: '🗄️', names: ['file_cabinet', 'storage', 'database', 'db', 'archive'] },
  // Status & Misc
  { char: '✅', names: ['check', 'done', 'complete', 'approved', 'tick', 'success', 'yes', 'green_check'] },
  { char: '❌', names: ['cross', 'no', 'wrong', 'error', 'x', 'cancel', 'delete', 'failed', 'nope'] },
  { char: '⚠️', names: ['warning', 'caution', 'danger', 'alert', 'warn'] },
  { char: '🚨', names: ['alert', 'siren', 'emergency', 'alarm', 'sos'] },
  { char: '🚫', names: ['no', 'prohibited', 'ban', 'forbidden', 'blocked'] },
  { char: '🔴', names: ['red_circle', 'red', 'stop', 'offline', 'error'] },
  { char: '🟡', names: ['yellow_circle', 'yellow', 'warning', 'caution', 'medium'] },
  { char: '🟢', names: ['green_circle', 'green', 'online', 'go', 'active', 'pass'] },
  { char: '🔵', names: ['blue_circle', 'blue', 'info'] },
  { char: '⚫', names: ['black_circle', 'dark', 'offline', 'disabled'] },
  { char: '❓', names: ['question', 'what', 'why', 'help', 'huh', 'unknown'] },
  { char: '❗', names: ['exclamation', 'important', 'bang', 'alert', 'attention'] },
  { char: '💬', names: ['speech_bubble', 'chat', 'comment', 'message', 'talk'] },
  { char: '📢', names: ['loudspeaker', 'announce', 'megaphone', 'broadcast', 'shout'] },
  { char: '🔔', names: ['bell', 'notification', 'alert', 'ring', 'notify'] },
  { char: '🔕', names: ['no_bell', 'silent', 'mute', 'no_sound', 'notifications_off'] },
  { char: '🔊', names: ['loud_sound', 'speaker', 'volume', 'audio', 'unmute'] },
  { char: '🔇', names: ['mute', 'no_sound', 'silent', 'speaker_off', 'quiet'] },
  { char: '⏰', names: ['alarm_clock', 'timer', 'wake_up', 'alarm'] },
  { char: '⏱️', names: ['stopwatch', 'timer', 'time', 'timing', 'countdown'] },
  { char: '⌛', names: ['hourglass', 'time', 'wait', 'loading', 'pending'] },
  { char: '⏳', names: ['hourglass_flow', 'time', 'wait', 'loading', 'pending', 'progress'] },
  { char: '📅', names: ['calendar', 'date', 'schedule', 'event', 'meeting'] },
  { char: '🗓️', names: ['spiral_calendar', 'date', 'schedule', 'planner'] },
  { char: '🚩', names: ['flag', 'red_flag', 'warning', 'important', 'flagged'] },
  { char: '🏁', names: ['checkered_flag', 'finish', 'race', 'done', 'complete', 'end'] },
  { char: '📍', names: ['round_pushpin', 'location', 'pin', 'place', 'here'] },
  { char: '🎯', names: ['bullseye', 'target', 'goal', 'dart', 'aim', 'focus'] },
  { char: '🧩', names: ['puzzle', 'jigsaw', 'piece', 'problem', 'missing_piece'] },
  { char: '🧲', names: ['magnet', 'attract', 'pull', 'magnetic'] },
  { char: '🔁', names: ['repeat', 'loop', 'cycle', 'refresh', 'again'] },
  { char: '🔄', names: ['refresh', 'reload', 'cycle', 'update', 'sync', 'rotate'] },
  { char: '🔀', names: ['shuffle', 'random', 'mix', 'swap'] },
  { char: '▶️', names: ['play', 'start', 'run', 'go', 'video', 'begin'] },
  { char: '⏸️', names: ['pause', 'stop', 'hold', 'break'] },
  { char: '⏹️', names: ['stop', 'square', 'halt', 'end'] },
  { char: '💯', names: ['100', 'perfect', 'hundred', 'score', 'full_marks', 'a_plus'] },
  { char: '💥', names: ['boom', 'explosion', 'collision', 'crash', 'bang', 'impact'] },
  { char: '🎉', names: ['party', 'tada', 'confetti', 'celebrate', 'congrats', 'yay', 'woo'] },
  { char: '🎊', names: ['confetti_ball', 'party', 'celebrate', 'woo'] },
  { char: '🎁', names: ['gift', 'present', 'wrap', 'birthday', 'surprise'] },
  { char: '🏆', names: ['trophy', 'winner', 'award', 'champion', 'gold', 'prize', 'best'] },
  { char: '🥇', names: ['gold_medal', 'first', 'winner', 'champion', 'gold', '1st'] },
  { char: '🎮', names: ['video_game', 'game', 'controller', 'gaming', 'console'] },
  { char: '🎵', names: ['musical_note', 'music', 'note', 'song', 'tune'] },
  { char: '🎶', names: ['musical_notes', 'music', 'song', 'melody', 'tunes'] },
  { char: '🎤', names: ['microphone', 'mic', 'sing', 'karaoke', 'performer'] },
  { char: '🎧', names: ['headphones', 'headset', 'music', 'listen', 'audio'] },
  // Travel & Misc
  { char: '✈️', names: ['airplane', 'plane', 'fly', 'travel', 'flight', 'trip'] },
  { char: '🚀', names: ['rocket', 'launch', 'space', 'fast', 'ship', 'deploy', 'blast'] },
  { char: '🚗', names: ['car', 'auto', 'drive', 'vehicle', 'road'] },
  { char: '🏠', names: ['house', 'home', 'building', 'shelter'] },
  { char: '🏖️', names: ['beach', 'vacation', 'sun', 'sand', 'holiday', 'summer'] },
  { char: '🌴', names: ['palm_tree', 'tropical', 'beach', 'vacation', 'coconut'] },
  { char: '🏔️', names: ['mountain', 'snow_capped', 'cold', 'climb', 'peak'] },
  { char: '💰', names: ['moneybag', 'rich', 'money', 'cash', 'dollar', 'wealth', 'bag'] },
  { char: '💳', names: ['credit_card', 'card', 'payment', 'debit', 'swipe'] },
  { char: '🛒', names: ['shopping_cart', 'cart', 'buy', 'shop', 'purchase'] },
  { char: '📣', names: ['megaphone', 'announce', 'broadcast', 'cheer', 'speak'] },
  { char: '⚗️', names: ['alembic', 'chemistry', 'lab', 'experiment', 'science'] },
  { char: '🧬', names: ['dna', 'genetics', 'science', 'biology', 'helix'] },
  { char: '🧪', names: ['test_tube', 'experiment', 'science', 'lab', 'chemistry'] },
  { char: '🌡️', names: ['thermometer', 'temperature', 'hot', 'fever', 'cold'] },
  { char: '🔐', names: ['locked_key', 'secure', 'password', 'encryption', 'auth'] },
  { char: '🛡️', names: ['shield', 'protect', 'defense', 'security', 'safe'] },
  { char: '⚔️', names: ['swords', 'crossed_swords', 'battle', 'fight', 'war', 'pvp'] },
  { char: '🏳️', names: ['white_flag', 'surrender', 'give_up', 'peace'] },
  { char: '↩️', names: ['return', 'back', 'reply', 'undo', 'left_arrow'] },
  { char: '↪️', names: ['forward', 'redo', 'go', 'right_arrow', 'next'] },
  { char: '➕', names: ['plus', 'add', 'new', 'positive', 'cross'] },
  { char: '➖', names: ['minus', 'subtract', 'remove', 'negative'] },
  { char: '💲', names: ['dollar_sign', 'money', 'cash', 'usd', 'currency'] },
  { char: '🧠', names: ['brain', 'smart', 'intelligence', 'think', 'mind', 'memory'] },
  { char: '👁️‍🗨️', names: ['eye_speech_bubble', 'awareness', 'see', 'witness'] },
  { char: '🌐', names: ['globe_with_meridians', 'internet', 'web', 'network', 'online', 'global'] },
  { char: '📻', names: ['radio', 'broadcast', 'listen', 'station', 'fm'] },
  { char: '🎙️', names: ['studio_microphone', 'podcast', 'record', 'broadcast', 'mic'] },
  { char: '📡', names: ['satellite_antenna', 'signal', 'dish', 'broadcast', 'network'] },
  { char: '🔮', names: ['crystal_ball', 'predict', 'magic', 'future', 'fortune'] },
  { char: '🎓', names: ['graduation', 'graduation_cap', 'academic', 'degree', 'learn', 'education'] },
  { char: '📚', names: ['books', 'library', 'reading', 'learn', 'study', 'knowledge'] },
  { char: '📖', names: ['open_book', 'read', 'reading', 'manual', 'documentation', 'docs'] },
  { char: '🧭', names: ['compass', 'direction', 'navigate', 'north', 'guide'] },
  { char: '⛽', names: ['fuel', 'gas', 'pump', 'petrol', 'energy'] },
  { char: '🧯', names: ['fire_extinguisher', 'emergency', 'safety', 'fire', 'danger'] },
  { char: '🎬', names: ['clapper', 'movie', 'film', 'cinema', 'action', 'scene'] },
  { char: '🎨', names: ['art', 'palette', 'paint', 'design', 'creative', 'artist'] },
  { char: '✒️', names: ['black_nib', 'pen', 'write', 'ink', 'sign'] },
  { char: '📌', names: ['pushpin', 'pin', 'location', 'mark', 'important'] },
  { char: '📎', names: ['paperclip', 'attach', 'link', 'clip', 'attachment'] },
]

export function searchEmoji(query: string, limit = 8): EmojiEntry[] {
  if (!query) return []
  const q = query.toLowerCase()
  const seen = new Set<string>()
  const results: EmojiEntry[] = []

  for (const entry of EMOJI_LIST) {
    if (results.length >= limit) break
    if (seen.has(entry.char)) continue
    if (entry.names.some((name) => name.includes(q))) {
      seen.add(entry.char)
      results.push(entry)
    }
  }

  return results
}
